import 'challenge_data.dart';

/// Static curated catalog of 21-day wellness exercises and ambient natural sounds.
class ChallengeCatalog {
  ChallengeCatalog._();

  /// 7 Natural Ambient Soundscapes from the project library.
  static const List<AmbientSound> allSounds = [
    AmbientSound(
      id: 'sound-forest-ambience',
      name: 'Bosque Profundo',
      category: 'nature',
      audioUrl: 'assets/sounds/forest_ambience.mp3',
    ),
    AmbientSound(
      id: 'sound-forest-birds',
      name: 'Canto de Pájaros',
      category: 'nature',
      audioUrl: 'assets/sounds/forest_birds.mp3',
    ),
    AmbientSound(
      id: 'sound-forest-wind',
      name: 'Viento & Aves del Bosque',
      category: 'nature',
      audioUrl: 'assets/sounds/forest_wind.mp3',
    ),
    AmbientSound(
      id: 'sound-river-sounds',
      name: 'Corriente de Río Silvestre',
      category: 'nature',
      audioUrl: 'assets/sounds/river_sounds.mp3',
    ),
    AmbientSound(
      id: 'sound-ocean-waves',
      name: 'Olas del Océano',
      category: 'nature',
      audioUrl: 'assets/sounds/ocean_waves.mp3',
    ),
    AmbientSound(
      id: 'sound-rain-thunder',
      name: 'Lluvia con Truenos Suaves',
      category: 'nature',
      audioUrl: 'assets/sounds/rain_thunder.mp3',
    ),
    AmbientSound(
      id: 'sound-nature-ambience',
      name: 'Serenidad Natural Inmersiva',
      category: 'nature',
      audioUrl: 'assets/sounds/nature_ambience.mp3',
    ),
  ];

  /// 21 Days of Guided High-Performance Meditation
  static const List<WellnessExercise> meditationExercises = [
    WellnessExercise(
      id: 'med-d1',
      challengeType: ChallengeType.meditation,
      dayNumber: 1,
      title: 'Respiración Consciente (4-4-4)',
      tip: 'Inhala en 4s, sostén en 4s y exhala en 4s para estabilizar la variabilidad cardíaca.',
      instructions: '1. Siéntate erguido con hombros relajados.\n2. Cierra los ojos o enfoca la vista hacia el suelo.\n3. Inhala lentamente por la nariz llenando abdomen y pecho (4s).\n4. Retén el aire sin tensión (4s).\n5. Exhala de forma fluida y continua (4s).\n6. Repite durante toda la sesión observando el flujo del aire en tus fosas nasales.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'med-d2',
      challengeType: ChallengeType.meditation,
      dayNumber: 2,
      title: 'Escaneo Corporal Completo (Body Scan)',
      tip: 'La propiocepción somática desconecta la red neuronal por defecto (DMN).',
      instructions: '1. Coloca tu atención en los dedos de los pies.\n2. Sube gradualmente: pantorrillas, rodillas, muslos, pelvis, abdomen.\n3. Nota cualquier microtensión acumulada y exhálala mentalmente.\n4. Continúa por el pecho, hombros, cuello, mandíbula y entrecejo.\n5. Permite que todo tu cuerpo repose en peso muerto sobre la superficie.',
      durationMinutes: 7,
    ),
    WellnessExercise(
      id: 'med-d3',
      challengeType: ChallengeType.meditation,
      dayNumber: 3,
      title: 'Coherencia Cardíaca 5.5s',
      tip: '6 respiraciones por minuto optimizan la sincronización barorrefleja del corazón.',
      instructions: '1. Inhala suavemente durante 5.5 segundos.\n2. Exhala sin pausas forzadas durante 5.5 segundos.\n3. Imagina que el aire entra y sale directamente a través del centro de tu pecho.\n4. Mantén un ritmo circular y fluido como las olas de la marea.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'med-d4',
      challengeType: ChallengeType.meditation,
      dayNumber: 4,
      title: 'El Observador Estoico',
      tip: 'Tú no eres tus pensamientos; eres la conciencia silenciosa que los atestigua.',
      instructions: '1. Imagina tu mente como un cielo azul inmutable.\n2. Cada pensamiento es una nube que cruza: no la empujes ni te subas a ella.\n3. Nombra suavemente lo que surge: "planificación", "recuerdo", "ansiedad".\n4. Déjalo pasar y regresa la atención a la sensación física de tu respiración.',
      durationMinutes: 8,
    ),
    WellnessExercise(
      id: 'med-d5',
      challengeType: ChallengeType.meditation,
      dayNumber: 5,
      title: 'Respiración Cuadrada (Box Breathing)',
      tip: 'Técnica de control autonómico empleada por operadores tácticos para bajar el cortisol.',
      instructions: '1. Inhala en 4 segundos.\n2. Sostén a pulmones llenos en 4 segundos.\n3. Exhala en 4 segundos.\n4. Sostén a pulmones vacíos en 4 segundos.\n5. Siente la quietud absoluta en las pausas entre ciclos respiratorios.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'med-d6',
      challengeType: ChallengeType.meditation,
      dayNumber: 6,
      title: 'Visualización de Claridad Ejecutiva',
      tip: 'La corteza motora y prefrontal ensayan el éxito conductual antes de actuar.',
      instructions: '1. Trae a tu mente el desafío principal de tu jornada.\n2. Visualízate abordándolo con compostura, serenidad y precisión quirúrgica.\n3. Siente en tu cuerpo la satisfacción de resolverlo con excelencia.\n4. Guarda esa sensación somática para anclarla durante tus horas de trabajo.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'med-d7',
      challengeType: ChallengeType.meditation,
      dayNumber: 7,
      title: 'Silencio Puro y Calibración Basal',
      tip: 'El silencio acústico permite la regeneración de neuronas en el hipocampo.',
      instructions: '1. Apaga cualquier estímulo externo y activa un sonido de lluvia o bosque.\n2. Renuncia por 7 minutos a solucionar, producir o evaluar nada.\n3. Descansa en la pura presencia de existir en el instante presente.',
      durationMinutes: 7,
    ),
    WellnessExercise(
      id: 'med-d8',
      challengeType: ChallengeType.meditation,
      dayNumber: 8,
      title: 'Gratitud Somática & Serotonina',
      tip: 'Evocar gratitud profunda incrementa la actividad del córtex cingulado anterior.',
      instructions: '1. Evoca a una persona o circunstancia por la que sientas genuina gratitud.\n2. No te limites al concepto verbal: localiza la calidez en tu pecho o garganta.\n3. Expande esa calidez con cada inhalación hacia todo tu cuerpo.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'med-d9',
      challengeType: ChallengeType.meditation,
      dayNumber: 9,
      title: 'Atención Focalizada (Trataka Mental)',
      tip: 'Entrena la densidad sináptica en la corteza prefrontal dorsolateral.',
      instructions: '1. Elige un punto único: el roce del aire en el labio superior o un punto mental.\n2. Cada vez que tu mente divague, reconócelo sin molestarte y vuelve al punto.\n3. Cada retorno es como una repetición de fuerza para tu músculo atencional.',
      durationMinutes: 8,
    ),
    WellnessExercise(
      id: 'med-d10',
      challengeType: ChallengeType.meditation,
      dayNumber: 10,
      title: 'Aceptación Radical (Amor Fati)',
      tip: 'La fricción mental nace de resistir la realidad. Acepta los hechos para actuar con poder.',
      instructions: '1. Identifica una situación reciente que no salió según tus planes.\n2. Respira profundamente y decreta mentalmente: "Acepto esto exactamente como ocurrió".\n3. Observa cómo el cuerpo suelta la tensión reactiva al cesar la resistencia.',
      durationMinutes: 7,
    ),
    WellnessExercise(
      id: 'med-d11',
      challengeType: ChallengeType.meditation,
      dayNumber: 11,
      title: 'Respiración 4-7-8 (Activación Parasimpática)',
      tip: 'Estimulación del nervio vago para inducir calma biológica inmediata.',
      instructions: '1. Coloca la punta de la lengua en el paladar, tras los dientes incisivos.\n2. Inhala por la nariz en 4 segundos.\n3. Retén el aire durante 7 segundos.\n4. Exhala por la boca haciendo un suave sonido de alivio durante 8 segundos.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'med-d12',
      challengeType: ChallengeType.meditation,
      dayNumber: 12,
      title: 'Perspectiva Cósmica (Memento Mori)',
      tip: 'Recordar la finitud humana destruye la trivialidad y enfoca en lo verdaderamente esencial.',
      instructions: '1. Imagina la tierra vista desde la órbita espacial.\n2. Contempla la brevedad de este día en la inmensidad del tiempo.\n3. Pregúntate con serenidad: "¿Qué merece realmente mi energía en este día irrepetible?".',
      durationMinutes: 7,
    ),
    WellnessExercise(
      id: 'med-d13',
      challengeType: ChallengeType.meditation,
      dayNumber: 13,
      title: 'Enraizamiento Sensorial (Grounding)',
      tip: 'Conectar con los 5 sentidos frena en seco los bucles de sobrepensamiento.',
      instructions: '1. Nota 3 texturas táctiles en tu piel o ropa.\n2. Escucha 3 sonidos distintos en el audio ambiental.\n3. Percibe la temperatura del aire en tu rostro.\n4. Siéntete completamente anclado al espacio físico que habitas.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'med-d14',
      challengeType: ChallengeType.meditation,
      dayNumber: 14,
      title: 'La Ciudadela Interior',
      tip: 'Marco Aurelio enseñó que el alma posee una fortaleza donde ningún evento exterior puede penetrar.',
      instructions: '1. Visualiza dentro de tu pecho una cámara inexpugnable de calma estoica.\n2. Los ruidos y presiones del exterior quedan fuera de sus murallas.\n3. Habita esa cámara sabiendo que tu centro no puede ser perturbado sin tu permiso.',
      durationMinutes: 8,
    ),
    WellnessExercise(
      id: 'med-d15',
      challengeType: ChallengeType.meditation,
      dayNumber: 15,
      title: 'Respiración Nasal & Óxido Nítrico',
      tip: 'La inhalación nasal calienta, filtra y aumenta la oxigenación arterial un 15-20%.',
      instructions: '1. Mantén los labios suavemente sellados y la lengua pegada al paladar.\n2. Inhala exclusivamente por la nariz de manera lenta, profunda y silenciosa.\n3. Siente cómo el aire nutre la base de tus pulmones sin levantar los hombros.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'med-d16',
      challengeType: ChallengeType.meditation,
      dayNumber: 16,
      title: 'Descompresión de Mandíbula y Cuello',
      tip: 'El estrés y la sobreexigencia suelen somatizarse en los maseteros y trapecios.',
      instructions: '1. Deja caer la mandíbula separando ligeramente los dientes molares.\n2. Permite que los hombros desciendan 2 centímetros lejos de tus orejas.\n3. Con cada exhalación, imagina que la rigidez se disuelve como cera tibia.',
      durationMinutes: 7,
    ),
    WellnessExercise(
      id: 'med-d17',
      challengeType: ChallengeType.meditation,
      dayNumber: 17,
      title: 'Premeditatio Malorum (Inoculación al Estrés)',
      tip: 'Anticipar mentalmente la fricción elimina el factor sorpresa y la histeria emocional.',
      instructions: '1. Trae a tu mente un posible contratiempo que temas para esta semana.\n2. Míralo de frente con compostura: no es el fin del mundo.\n3. Decide con calma tu respuesta racional ante ese escenario.',
      durationMinutes: 8,
    ),
    WellnessExercise(
      id: 'med-d18',
      challengeType: ChallengeType.meditation,
      dayNumber: 18,
      title: 'Desintoxicación de Dopamina Sensorial',
      tip: 'Reducir la hiperestimulación restablece la sensibilidad de los receptores D2.',
      instructions: '1. Cierra los ojos y atiende únicamente a la textura del sonido de la naturaleza.\n2. No busques entretenimiento; permite que tu cerebro abrace la calma sin prisa.',
      durationMinutes: 8,
    ),
    WellnessExercise(
      id: 'med-d19',
      challengeType: ChallengeType.meditation,
      dayNumber: 19,
      title: 'Anclaje del Suspiro Fisiológico',
      tip: 'Dos inhalaciones cortas seguidas de una exhalación larga colapsan el estrés en segundos.',
      instructions: '1. Realiza una primera inhalación nasal profunda.\n2. Sin exhalar, toma una microinhalación adicional al final para expandir los alvéolos.\n3. Exhala lentamente por la boca liberando todo el aire acumulado.\n4. Realiza 5 repeticiones de este suspiro y luego continúa respirando normalmente.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'med-d20',
      challengeType: ChallengeType.meditation,
      dayNumber: 20,
      title: 'Empatía Estratégica y Buenas Relaciones',
      tip: 'El liderazgo consciente requiere comprender los motivos ajenos con serenidad reflexiva.',
      instructions: '1. Piensa en una persona con quien hayas tenido diferencias de criterio.\n2. Reconoce que también actúa buscando bienestar según su nivel de comprensión.\n3. Deséale claridad y mantén tu intención en colaborar desde la excelencia.',
      durationMinutes: 7,
    ),
    WellnessExercise(
      id: 'med-d21',
      challengeType: ChallengeType.meditation,
      dayNumber: 21,
      title: 'Maestría de la Mente Imperturbable',
      tip: 'Culminación del reto de 21 días: La meditación ya es tu ancla de alto rendimiento.',
      instructions: '1. Siéntate con dignidad y gratitud por haber perseverado los 21 días.\n2. Respira en libertad, reconociendo el dominio que has forjado sobre tu atención.\n3. Comprométete a regresar a esta respiración siempre que la vida te exija maestría.',
      durationMinutes: 10,
    ),
  ];

  /// 21 Days of Yoga & Spinal Postural Mastery
  static const List<WellnessExercise> yogaExercises = [
    WellnessExercise(
      id: 'yoga-d1',
      challengeType: ChallengeType.yoga,
      dayNumber: 1,
      title: 'Tadasana (Postura de la Montaña)',
      tip: 'Base de toda postura de pie. Calibra la distribución plantar y el eje axial.',
      instructions: '1. Pies juntos o al ancho de caderas. Distribuye el peso en los 4 puntos de la planta.\n2. Activa cuádriceps, retroversión pélvica sutil y activa el transverso abdominal.\n3. Rueda los hombros atrás y abajo, coronilla apuntando al cielo.\n4. Sostén respirando profundamente 10 ciclos.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yoga-d2',
      challengeType: ChallengeType.yoga,
      dayNumber: 2,
      title: 'Balasana (Postura del Niño)',
      tip: 'Descomprime las vértebras lumbares y envía señal de calma al sistema nervioso.',
      instructions: '1. De rodillas, junta los dedos gordos de los pies y separa las rodillas al ancho del tapete.\n2. Lleva las caderas hacia los talones y camina con las manos hacia adelante.\n3. Apoya la frente en el suelo y alarga los costados del torso.\n4. Respira llevando el aire hacia la parte baja de la espalda.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yoga-d3',
      challengeType: ChallengeType.yoga,
      dayNumber: 3,
      title: 'Marjaryasana-Bitilasana (Gato-Vaca)',
      tip: 'Lubrica el líquido sinovial entre discos intervertebrales y disuelve rigidez.',
      instructions: '1. Cuatro puntos de apoyo: muñecas bajo hombros, rodillas bajo caderas.\n2. Vaca: Inhala, eleva cóccix y mirada, arquea suavemente la columna.\n3. Gato: Exhala, redondea la espalda llevando el ombligo a la columna y barbilla al pecho.\n4. Fluye entre ambas posturas durante 12 respiraciones completas.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yoga-d4',
      challengeType: ChallengeType.yoga,
      dayNumber: 4,
      title: 'Adho Mukha Svanasana (Perro Boca Abajo)',
      tip: 'Elongación de isquiotibiales, fortalecimiento escapular y descompresión cervical.',
      instructions: '1. Desde cuatro puntos, apoya metatarsos y eleva caderas hacia arriba y atrás.\n2. Manos bien enraizadas, dedos abiertos, presiona el suelo lejos de ti.\n3. Puedes flexionar ligeramente las rodillas para priorizar una columna recta.\n4. Rota externamente los hombros alejándolos de las orejas. Sostén 8 respiraciones.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'yoga-d5',
      challengeType: ChallengeType.yoga,
      dayNumber: 5,
      title: 'Bhujangasana (Postura de la Cobra)',
      tip: 'Abre la caja torácica, contrarresta la postura encorvada del trabajo frente a pantallas.',
      instructions: '1. Acostado boca abajo, manos a los lados del pecho, codos pegados a las costillas.\n2. Empeines firmes en el suelo, activa glúteos y piernas.\n3. Inhala y eleva pecho sin forzar con los brazos, utilizando la musculatura dorsal.\n4. Hombros lejos de las orejas y cuello en línea con la columna. Sostén 5 respiraciones x 3 rondas.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yoga-d6',
      challengeType: ChallengeType.yoga,
      dayNumber: 6,
      title: 'Surya Namaskar A (Saludo al Sol)',
      tip: 'Secuencia clásica para elevar la temperatura corporal y sincronizar respiración y movimiento.',
      instructions: '1. Montaña → Inhala brazos arriba → Exhala pliegue al frente (Uttanasana).\n2. Inhala media elevación (Ardha) → Exhala tabla y baja suave (Chaturanga).\n3. Inhala Cobra o Perro Boca Arriba → Exhala Perro Boca Abajo (sostén 5 resp).\n4. Inhala camina al frente → Exhala pliegue → Inhala eleva torso y brazos.\n5. Realiza 3 vueltas conscientes.',
      durationMinutes: 7,
    ),
    WellnessExercise(
      id: 'yoga-d7',
      challengeType: ChallengeType.yoga,
      dayNumber: 7,
      title: 'Virabhadrasana I (Guerrero I)',
      tip: 'Fortalecimiento de piernas, estabilidad pélvica y expansión del psoas.',
      instructions: '1. Da un paso largo atrás con el pie izquierdo a 45 grados, talón en el suelo.\n2. Flexiona rodilla delantera a 90 grados sobre el tobillo.\n3. Cuadra las caderas hacia el frente y eleva los brazos al cielo.\n4. Sostén 5 respiraciones por lado.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'yoga-d8',
      challengeType: ChallengeType.yoga,
      dayNumber: 8,
      title: 'Virabhadrasana II (Guerrero II)',
      tip: 'Fomenta el foco mental inquebrantable a través del Drishti (mirada enfocada).',
      instructions: '1. Pies separados 1 metro, pie delantero apunta al frente, trasero a 90 grados.\n2. Flexiona rodilla delantera sobre el tobillo y abre brazos en cruz a la altura de hombros.\n3. Fija la mirada con determinación por encima de los dedos de la mano delantera.\n4. Sostén 6 respiraciones lentas por cada lado.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'yoga-d9',
      challengeType: ChallengeType.yoga,
      dayNumber: 9,
      title: 'Vrikshasana (Postura del Árbol)',
      tip: 'Entrenamiento propioceptivo del equilibrio y serenidad del sistema vestibular.',
      instructions: '1. En Tadasana, traslada el peso a la pierna izquierda.\n2. Coloca la planta del pie derecho en la pantorrilla o muslo interno (nunca en la rodilla).\n3. Junta palmas al centro del pecho o elévalas al cielo.\n4. Fija un punto visual inmóvil frente a ti. Sostén 30-45 segundos por lado.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yoga-d10',
      challengeType: ChallengeType.yoga,
      dayNumber: 10,
      title: 'Trikonasana (El Triángulo Extendido)',
      tip: 'Elonga los isquiotibiales y abre los oblicuos torácicos favoreciendo la capacidad pulmonar.',
      instructions: '1. Piernas abiertas, pie delantero apunta al frente, trasero a 90 grados.\n2. Inhala extiende brazos, exhala alarga torso hacia adelante y baja la mano a la espinilla o bloque.\n3. Brazo opuesto apunta verticalmente hacia el cielo.\n4. Abre el pecho girando el torso hacia el lateral. Sostén 5 respiraciones por lado.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'yoga-d11',
      challengeType: ChallengeType.yoga,
      dayNumber: 11,
      title: 'Setu Bandhasana (Medio Puente)',
      tip: 'Tonifica glúteos e isquiotibiales mientras descomprime el pecho y la tiroides.',
      instructions: '1. Acostado boca arriba, flexiona rodillas y apoya pies al ancho de caderas.\n2. Brazos a los lados con palmas hacia abajo o entrelazando dedos bajo la espalda.\n3. Presiona los talones y eleva caderas al cielo activando los glúteos.\n4. Mantén los muslos paralelos sin abrir rodillas. Sostén 6 respiraciones x 3 rondas.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'yoga-d12',
      challengeType: ChallengeType.yoga,
      dayNumber: 12,
      title: 'Paschimottanasana (Pinza Sentada)',
      tip: 'Estiramiento profundo de toda la cadena fascial posterior y calma mental reflexiva.',
      instructions: '1. Siéntate con piernas extendidas al frente y pies en flex.\n2. Inhala alargando la columna hacia arriba con brazos elevados.\n3. Exhala flexionando desde las caderas hacia los pies (no desde la zona dorsal).\n4. Toma pantorrillas, tobillos o pies; relaja la cabeza y respira profundamente 10 ciclos.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yoga-d13',
      challengeType: ChallengeType.yoga,
      dayNumber: 13,
      title: 'Utkatasana (Postura de la Silla)',
      tip: 'Forja fuerza en cuádriceps, glúteos y templanza psicológica ante el esfuerzo isométrico.',
      instructions: '1. Pies juntos o al ancho de caderas. Inhala y eleva brazos paralelos a las orejas.\n2. Exhala flexionando rodillas como sentándote en una silla imaginaria profunda.\n3. Peso en los talones, mantén el pecho abierto y el ombligo adentro.\n4. Sostén durante 8 respiraciones firmes.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yoga-d14',
      challengeType: ChallengeType.yoga,
      dayNumber: 14,
      title: 'Ardha Matsyendrasana (Torsión Espinal Sentada)',
      tip: 'Favorece la movilidad rotacional de la columna y estimula la digestión visceral.',
      instructions: '1. Siéntate con piernas cruzadas o pierna derecha flexionada sobre la izquierda extendida.\n2. Mano derecha detrás de la cadera como soporte firme.\n3. Inhala eleva brazo izquierdo, exhala abraza la rodilla o engancha el codo por fuera.\n4. Gira la mirada por encima del hombro derecho con cada exhalación. 5 resp por lado.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'yoga-d15',
      challengeType: ChallengeType.yoga,
      dayNumber: 15,
      title: 'Anjaneyasana (Estocada Baja)',
      tip: 'Elonga el psoas ilíaco, fundamental para quienes pasan horas sentados en escritorio.',
      instructions: '1. Desde cuatro puntos, lleva el pie derecho adelante entre las manos.\n2. Apoya la rodilla izquierda atrás en el suelo y desciende las caderas hacia el tapete.\n3. Inhala y eleva el torso y los brazos abriendo el pecho suavemente.\n4. Siente la descarga profunda en la ingle izquierda. Sostén 6 respiraciones por lado.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'yoga-d16',
      challengeType: ChallengeType.yoga,
      dayNumber: 16,
      title: 'Salabhasana (La Langosta)',
      tip: 'Fortalece los músculos erectores de la columna, romboides y glúteos.',
      instructions: '1. Boca abajo con brazos a los lados del cuerpo, palmas hacia el suelo.\n2. Inhala y eleva simultáneamente pecho, brazos y piernas del suelo.\n3. Mirada suave hacia el suelo para no pellizcar las cervicales.\n4. Sostén la fuerza dorsal 5 respiraciones x 3 repeticiones.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yoga-d17',
      challengeType: ChallengeType.yoga,
      dayNumber: 17,
      title: 'Malasana (Sentadilla Profunda Yóguica)',
      tip: 'Restaura la movilidad biomecánica de la cadera y tobillos.',
      instructions: '1. Separa los pies un poco más del ancho de caderas con puntas hacia afuera.\n2. Desciende en sentadilla completa llevando caderas hacia los talones.\n3. Junta palmas al centro del pecho y empuja suavemente las rodillas con los codos.\n4. Alarga la columna erguida sin colapsar el pecho. Sostén 8 respiraciones.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yoga-d18',
      challengeType: ChallengeType.yoga,
      dayNumber: 18,
      title: 'Gomukhasana (Brazos de Cara de Vaca)',
      tip: 'Libera la rigidez de manguito rotador y pectorales cerrados por uso de teclado.',
      instructions: '1. Siéntate erguido. Eleva brazo derecho, flexiona el codo llevando la mano a la espalda.\n2. Lleva el brazo izquierdo por debajo e intenta enganchar los dedos de ambas manos.\n3. Si no alcanzas, utiliza una toalla o cinta.\n4. Mantén la cabeza erguida sin empujar hacia abajo. Sostén 6 respiraciones por lado.',
      durationMinutes: 6,
    ),
    WellnessExercise(
      id: 'yoga-d19',
      challengeType: ChallengeType.yoga,
      dayNumber: 19,
      title: 'Viparita Karani (Piernas en la Pared)',
      tip: 'Potencia el retorno venoso, desinflama piernas y descarga el corazón.',
      instructions: '1. Acerca las caderas a una pared y acuéstate boca arriba elevando las piernas verticales.\n2. Brazos relajados a los costados en cruz o sobre el abdomen.\n3. Cierra los ojos y permite que la gravedad descomprima la circulación de tus extremidades.\n4. Permanece de 5 a 7 minutos en calma absoluta.',
      durationMinutes: 7,
    ),
    WellnessExercise(
      id: 'yoga-d20',
      challengeType: ChallengeType.yoga,
      dayNumber: 20,
      title: 'Surya Namaskar B (Saludo al Sol Dinámico)',
      tip: 'Flujo aeróbico estructurado que integra Silla y Guerreros en movimiento continuo.',
      instructions: '1. Inicia en Utkatasana (Silla) → Pliegue → Chaturanga → Cobra/Urddhva → Perro Abajo.\n2. Guerrero I pierna derecha → Chaturanga → Perro Abajo.\n3. Guerrero I pierna izquierda → Chaturanga → Perro Abajo (5 respiraciones).\n4. Regresa al frente en Utkatasana y vuelve a Tadasana. Realiza 2 vueltas completas.',
      durationMinutes: 8,
    ),
    WellnessExercise(
      id: 'yoga-d21',
      challengeType: ChallengeType.yoga,
      dayNumber: 21,
      title: 'Savasana & Alineación Postural Integrada',
      tip: 'La postura de integración más importante: permite al sistema nervioso asimilar las adaptaciones.',
      instructions: '1. Acuéstate completamente boca arriba, piernas separadas y pies cayendo a los lados.\n2. Brazos a 45 grados con palmas hacia arriba.\n3. Suelta todo control de la respiración y del cuerpo físico.\n4. Descansa en la quietud profunda sabiendo que has forjado una columna y mente más fuertes.',
      durationMinutes: 10,
    ),
  ];

  /// 21 Days of Facial Yoga & Lymphatic Toning
  static const List<WellnessExercise> yogaFacialExercises = [
    WellnessExercise(
      id: 'yf-d1',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 1,
      title: 'Drenaje Linfático Clavicular & Cuello',
      tip: 'Abre las vías linfáticas para que los líquidos y toxinas del rostro puedan drenar.',
      instructions: '1. Aplica una gota de aceite facial o crema hidratante en cuello y mandíbula.\n2. Con las yemas de los dedos, haz movimientos descendentes suaves desde detrás de las orejas hacia las clavículas.\n3. Bombea suavemente 10 veces en el hueco sobre la clavícula.\n4. Repite el deslizamiento suave 15 veces a cada lado sin apretar.',
      durationMinutes: 4,
    ),
    WellnessExercise(
      id: 'yf-d2',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 2,
      title: 'La "V" para Contorno de Ojos',
      tip: 'Fortalece el músculo orbicular de los párpados y alivia bolsas por fatiga digital.',
      instructions: '1. Forma una "V" con los dedos índice y medio de ambas manos.\n2. Coloca el dedo medio en la comisura interna del ojo y el índice en la externa.\n3. Mira hacia arriba y entrecierra los ojos solo con el párpado inferior sintiendo el temblor muscular.\n4. Sostén 5 segundos y relaja. Realiza 8 repeticiones.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d3',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 3,
      title: 'Elevador de Pómulos (La Sonrisa Abierta)',
      tip: 'Activa los músculos cigomáticos mayor y menor para elevar el tercio medio facial.',
      instructions: '1. Cubre los dientes superiores con los labios formando una "O" alargada.\n2. Desde esa postura, sonríe ampliamente usando solo las comisuras de la boca para subir los pómulos.\n3. Coloca los dedos índices suavemente sobre los pómulos para notar la contracción.\n4. Sube y relaja 15 veces a ritmo constante.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d4',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 4,
      title: 'Definición de Mandíbula con Pinza de Dedos',
      tip: 'Tonifica el músculo platisma y estiliza el borde mandibular.',
      instructions: '1. Dobla los dedos índice y medio de una mano en forma de gancho (nudillos).\n2. Atrapa el hueso de la mandíbula entre ambos nudillos, empezando en la barbilla.\n3. Desliza con presión media firme a lo largo del hueso hacia el lóbulo de la oreja.\n4. Realiza 12 pasadas por cada lado con calma y fluidez.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d5',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 5,
      title: 'Alisado de Frente (El Peine Horizontal)',
      tip: 'Desactiva la tensión del músculo frontal y atenúa líneas horizontales.',
      instructions: '1. Coloca las yemas de todos los dedos en el centro de tu frente.\n2. Con una presión suave pero firme, barre horizontalmente hacia las sienes.\n3. Al llegar a las sienes, haz un suave círculo de descompresión.\n4. Realiza 15 pasadas lentas y respirando hondo.',
      durationMinutes: 4,
    ),
    WellnessExercise(
      id: 'yf-d6',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 6,
      title: 'Liberación de Maseteros (Antibruxismo)',
      tip: 'El masetero es uno de los músculos más potentes del cuerpo y acumula tensión oculta.',
      instructions: '1. Con los puños cerrados, usa los nudillos para presionar justo debajo del pómulo, en la mandíbula.\n2. Abre y cierra la boca lentamente sintiendo el músculo masetero deslizarse bajo tus nudillos.\n3. Masajea en pequeños círculos descendentes durante 2 minutos.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d7',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 7,
      title: 'Tonificación Peribucal (La "O" Tónica)',
      tip: 'Mantiene firme el orbicular de los labios y previene líneas verticales.',
      instructions: '1. Oculta los labios hacia adentro sobre los dientes.\n2. Forma una "O" pequeña y tensa con la boca.\n3. Usa los dedos índices para aplicar golpecitos ligeros alrededor de los labios.\n4. Sostén la "O" durante 20 segundos x 3 repeticiones.',
      durationMinutes: 4,
    ),
    WellnessExercise(
      id: 'yf-d8',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 8,
      title: 'Lifting de Párpados Caídos',
      tip: 'Aumenta la fuerza del músculo elevador del párpado superior para abrir la mirada.',
      instructions: '1. Coloca los dedos índices debajo de las cejas, manteniéndolas en su sitio sin dejarlas subir.\n2. Intenta cerrar los ojos lentamente contra la resistencia suave de tus dedos.\n3. Siente el estiramiento y contracción del párpado.\n4. Sostén 5 segundos cerrado y abre. Realiza 10 repeticiones.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d9',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 9,
      title: 'El Cisne (Estiramiento de Cuello & Escote)',
      tip: 'Elonga el platisma y mejora la postura cervical contra el "text neck".',
      instructions: '1. Gira la cabeza 45 grados a la derecha y elévala mirando hacia arriba.\n2. Saca ligeramente la mandíbula inferior hacia adelante sintiendo el estiramiento en el cuello.\n3. Sostén 10 segundos respirando. Regresa al centro y repite hacia la izquierda.\n4. Realiza 4 repeticiones por lado.',
      durationMinutes: 4,
    ),
    WellnessExercise(
      id: 'yf-d10',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 10,
      title: 'Puff de Aire para Mejillas Firmes',
      tip: 'Estimula el músculo buccinador para mantener terso el contorno de mejillas.',
      instructions: '1. Llena la boca con una burbuja de aire bajo el labio superior (sostén 5s).\n2. Pasa el aire hacia la mejilla derecha (5s).\n3. Pásalo al labio inferior (5s).\n4. Pásalo a la mejilla izquierda (5s).\n5. Repite el circuito circular durante 2 minutos continuos.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d11',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 11,
      title: 'Descongestión del Entrecejo (Procerus & Corrugator)',
      tip: 'Borra la huella de ceño fruncido producida por la concentración excesiva.',
      instructions: '1. Coloca el dedo índice o el pulgar en el entrecejo.\n2. Realiza movimientos en forma de "V" hacia arriba y hacia el inicio de las cejas.\n3. Luego pellizca suavemente la ceja desde el interior hacia la cola de la ceja.\n4. Realiza 10 pasadas respirando pausadamente.',
      durationMinutes: 4,
    ),
    WellnessExercise(
      id: 'yf-d12',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 12,
      title: 'Gua Sha Manual con Nudillos',
      tip: 'Efecto lifting inmediato mejorando la microcirculación cutánea.',
      instructions: '1. Aplica unas gotas de aceite facial.\n2. Con los nudillos del índice y corazón, desliza desde la comisura de la boca hacia las sienes.\n3. Mantén una inclinación suave para no irritar la piel.\n4. Realiza 12 movimientos en cada lado del rostro.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d13',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 13,
      title: 'El Pescado Sonriente',
      tip: 'Aísla los pómulos reduciendo la grasa subcutánea bucal.',
      instructions: '1. Succiona las mejillas hacia adentro entre los dientes como un pez.\n2. Desde esa posición, intenta sonreír con las comisuras hacia arriba.\n3. Sostén durante 10 segundos sintiendo el trabajo en los pómulos.\n4. Relaja y repite 5 rondas.',
      durationMinutes: 4,
    ),
    WellnessExercise(
      id: 'yf-d14',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 14,
      title: 'Acupresión Facial Revitalizante',
      tip: 'Estimula puntos reflejos para restaurar el tono vascular y la luminosidad.',
      instructions: '1. Presiona suavemente 10s el punto entre las cejas (Yintang).\n2. Presiona 10s los laterales de las aletas nasales (Yingxiang).\n3. Presiona 10s las sienes (Taiyang).\n4. Presiona 10s justo bajo los pómulos al nivel de la pupila.\n5. Siente el alivio de tensión y el calor circulatorio.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d15',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 15,
      title: 'El Gran Bostezo con Elongación',
      tip: 'Resetea la tensión mandibular de toda la articulación temporomandibular (ATM).',
      instructions: '1. Abre la boca de par en par como en un bostezo amplio y controlado.\n2. Dirige la mirada hacia el techo manteniendo la frente sin arrugas.\n3. Sostén 8 segundos y cierra lentamente.\n4. Realiza 5 repeticiones sintiendo la descarga fascial.',
      durationMinutes: 4,
    ),
    WellnessExercise(
      id: 'yf-d16',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 16,
      title: 'Elevación de Cejas con Resistencia',
      tip: 'Fortalece la frente sin crear arrugas superficiales.',
      instructions: '1. Apoya firmemente las palmas de las manos sobre la frente cubriéndola toda.\n2. Intenta levantar las cejas con fuerza mientras tus manos impiden que la piel se mueva.\n3. Sostén 6 segundos y relaja.\n4. Realiza 8 repeticiones.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d17',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 17,
      title: 'Drenaje del Surco Nasogeniano',
      tip: 'Suaviza las líneas de expresión que van de la nariz a la boca.',
      instructions: '1. Coloca las yemas de los pulgares bajo la barbilla y los índices sobre el surco nasogeniano.\n2. Desliza los índices hacia afuera y hacia arriba siguiendo la línea de los pómulos hasta las orejas.\n3. Realiza 15 pasadas suaves y constantes.',
      durationMinutes: 4,
    ),
    WellnessExercise(
      id: 'yf-d18',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 18,
      title: 'Masaje del Músculo Temporal',
      tip: 'Descomprime el dolor de cabeza tensional y eleva lateralmente la mirada.',
      instructions: '1. Coloca las yemas de cuatro dedos sobre las sienes y la zona lateral de la cabeza.\n2. Realiza círculos profundos y lentos hacia atrás durante 2 minutos.\n3. Abre la boca sutilmente mientras masajeas para maximizar la liberación.',
      durationMinutes: 4,
    ),
    WellnessExercise(
      id: 'yf-d19',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 19,
      title: 'El Beso al Techo (Anti-Papada)',
      tip: 'Tonifica el músculo milohioideo y digástrico bajo la mandíbula.',
      instructions: '1. Inclina suavemente la cabeza hacia atrás mirando al techo.\n2. Frunce los labios como lanzando un beso exagerado hacia arriba.\n3. Siente la tensión y trabajo en la zona submentoniana.\n4. Sostén 8 segundos x 6 repeticiones.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d20',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 20,
      title: 'Tapotement (Micro-Percusión de Colágeno)',
      tip: 'Estimula los fibroblastos para promover la síntesis de colágeno y elastina.',
      instructions: '1. Con las yemas de todos los dedos relajados, da golpecitos rápidos y ligeros como gotas de lluvia en todo el rostro.\n2. Cubre frente, pómulos, mejillas, mandíbula y cuello durante 2 minutos ininterrumpidos.\n3. Disfruta el cosquilleo y el despertar sensorial.',
      durationMinutes: 5,
    ),
    WellnessExercise(
      id: 'yf-d21',
      challengeType: ChallengeType.yogaFacial,
      dayNumber: 21,
      title: 'Ritual Facial Completo de Maestría',
      tip: 'Secuencia maestra integrada de 5 minutos: Drenaje + Tonificación + Tapotement.',
      instructions: '1. Drenaje clavicular (1 min).\n2. Elevador de pómulos y "O" tónica (2 min).\n3. Definición mandibular con nudillos (1 min).\n4. Tapotement final y reposo consciente (1 min).\n5. ¡Felicitaciones por culminar tus 21 días de Yoga Facial!',
      durationMinutes: 6,
    ),
  ];

  static List<WellnessExercise> get allExercises => [
        ...meditationExercises,
        ...yogaExercises,
        ...yogaFacialExercises,
      ];
}
